DROP TABLE IF EXISTS {{tableName}};
CREATE TABLE IF NOT EXISTS {{tableName}} (
    id_prv varchar NOT NULL,
	prv_db varchar NULL,
	prv_name varchar NOT NULL,
	prv_url varchar NULL,
	prs_manager varchar NULL,
	prv_type_id int4 NULL,
	prv_type varchar NULL,
	prs_state_id int4 NULL,
	prs_state varchar NULL,
	accept_status_id int4 NULL,
	accept_status varchar NULL,
	shema_id int4 NULL,
	shema varchar NULL,
	prv_add_date varchar NULL,
	contract_date_from varchar NULL,
	prv_first_txn_date varchar NULL,
	prv_last_txn_date varchar NULL,
	prv_add_timestamp timestamp NULL,
	prv_contract_timestamp timestamp NULL,
	prv_first_txn_timestamp timestamp NULL,
	prv_last_txn_timestamp timestamp NULL,
	agt_id varchar NULL,
	reject_cause varchar NULL,
	agregator varchar NULL,
	prv_global_name varchar NULL,
	prv_merch_name varchar NULL,
	prv_is_otp_auth_pay bool NULL,
	prv_is_unlinked_card_pay bool NULL,
	prv_mrkt_name varchar NULL,
	prv_mrkt_sub_name varchar NULL,
	prv_jur_name varchar NULL,
	replication_start_date timestamp NULL
);