INSERT
	INTO
		obj_provider(
		            prv_db,
        			id_prv,
        			prv_name,
        			prv_url,
        			prs_manager,
        			prv_type_id,
        			prv_type,
        			prs_state_id,
        			prs_state,
        			accept_status_id,
        			accept_status,
        			shema_id,
        			shema,
        			prv_add_date,
        			contract_date_from,
        			agregator,
        			prv_global_name,
        			prv_merch_name,
        			prv_first_txn_date,
        			prv_last_txn_date,
        			agt_id,
        			reject_cause,
        			prv_is_otp_auth_pay,
        			prv_is_unlinked_card_pay,
        			prv_mrkt_name,
        			prv_mrkt_sub_name,
        			prv_jur_name
		)(
			SELECT
				    prv_db,
                    id_prv,
                    prv_name,
                    prv_url,
                    prs_manager,
                    prv_type_id,
                    prv_type,
                    prs_state_id,
                    prs_state,
                    accept_status_id,
                    accept_status,
                    shema_id,
                    shema,
                    prv_add_date,
                    contract_date_from,
                    agregator,
                    prv_global_name,
                    prv_merch_name,
                    prv_first_txn_date,
                    prv_last_txn_date,
                    agt_id,
                    reject_cause,
                    prv_is_otp_auth_pay,
                    prv_is_unlinked_card_pay,
                    prv_mrkt_name,
                    prv_mrkt_sub_name,
                    prv_jur_name
			FROM
				{{tableName}}
		) ON CONFLICT (id_prv) DO UPDATE SET 
                     prv_db = EXCLUDED.prv_db,
                     id_prv = EXCLUDED.id_prv,
                     prv_name = EXCLUDED.prv_name,
                     prv_url = EXCLUDED.prv_url,
                     prs_manager = EXCLUDED.prs_manager,
                     prv_type_id = EXCLUDED.prv_type_id,
                     prv_type = EXCLUDED.prv_type,
                     prs_state_id = EXCLUDED.prs_state_id,
                     prs_state = EXCLUDED.prs_state,
                     accept_status_id = EXCLUDED.accept_status_id,
                     accept_status = EXCLUDED.accept_status,
                     shema_id = EXCLUDED.shema_id,
                     shema = EXCLUDED.shema,
                     prv_add_date = EXCLUDED.prv_add_date,
                     contract_date_from = EXCLUDED.contract_date_from,
                     agregator = EXCLUDED.agregator,
                     prv_global_name = EXCLUDED.prv_global_name,
                     prv_merch_name = EXCLUDED.prv_merch_name,
                     prv_first_txn_date = EXCLUDED.prv_first_txn_date,
                     prv_last_txn_date = EXCLUDED.prv_last_txn_date,
                     agt_id = EXCLUDED.agt_id,
                     reject_cause = EXCLUDED.reject_cause,
                     prv_is_otp_auth_pay = EXCLUDED.prv_is_otp_auth_pay,
                     prv_is_unlinked_card_pay = EXCLUDED.prv_is_unlinked_card_pay,
                     prv_mrkt_name = EXCLUDED.prv_mrkt_name,
                     prv_mrkt_sub_name = EXCLUDED.prv_mrkt_sub_name,
                     prv_jur_name = EXCLUDED.prv_jur_name